### PR TITLE
Fix/hide bottombar on tutorial revisit

### PR DESCRIPTION
**Pull request by bjornustwo**

### CODE REVIEW

**Comment by onnerfors** [comment]
works ⭐️ though sveta thought the user should remain on settings page having revisited the tutorial @bjornustwo

**Comment by bjornustwo** [comment]
I saw that. That would be a new feature though. It never worked that way.

**Comment by onnerfors** [comment]
OK, adding it to the backlog

**Comment by onnerfors** [comment]
Or maybe sveta put it there already... merge this anyway

**Pull request merged**
